default[:cc_rails_portal][:root] = "/web/cc_rails_portal"
default[:cc_rails_portal][:theme] = "xproject"
default[:cc_rails_portal][:name] = "Cross Project Portal"
default[:cc_rails_portal][:user] = "portal"
default[:cc_rails_portal][:checkout] = "true"
default[:cc_rails_portal][:source_url] = "git://github.com/stepheneb/rigse.git"
default[:cc_rails_portal][:source_branch] = "xproject-dev"
